# Generated by Django 6.0.2 on 2026-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('SCANNING', 'Scanning'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('scan_report', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
