# Generated by Django 6.0.2 on 2026-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
