# Generated by Django 6.0.2 on 2026-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='detections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='provider',
            field=models.CharField(default='VirusTotal', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='report_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='vt_analysis_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
